require 'Items/SuburbsDistributions'
require 'Items/ProceduralDistributions'

table.insert(ProceduralDistributions.list["CrateTools"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["CrateTools"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["GarageTools"].items, 1);
table.insert(ProceduralDistributions.list["GarageTools"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["GarageTools"].items, 1);
table.insert(ProceduralDistributions.list["MetalShopTools"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["MetalShopTools"].items, 1);
table.insert(ProceduralDistributions.list["MetalShopTools"].items, "traps.BearTraps");
table.insert(ProceduralDistributions.list["MetalShopTools"].items, 1);
table.insert(ProceduralDistributions.list["ToolStoreMetalwork"].items, "traps.BearTrap");
table.insert(ProceduralDistributions.list["ToolStoreMetalwork"].items, 1);
